apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ue5-build-task
spec:
  steps:
    - name: clone
      image: perforce/p4
      args:
        - p4
        - -c
        - $(inputs.params.p4-url)
        - -u
        - $(inputs.params.p4-username)
        - -P
        - $(inputs.params.p4-password)
        - sync
        - //...
      volumeMounts:
        - name: workspace
          mountPath: /workspace
    - name: setup-environment
      image: your-build-environment-image
      script: |
        echo "Running environment setup"
    - name: build-ue5-game
      image: ue5-build-image
      script: |
        curl https://raw.githubusercontent.com/tristanpoland/UE-Game-Build-Toolkit/main/BuildScript.sh?token=$GITHUB_TOKEN | sh