apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ue5-game-pipeline-run
spec:
  pipelineRef:
    name: ue5-game-pipeline
  params:
    - name: revision
      value: master  # Specify the revision to build
