apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ue5-game-pipeline
spec:
  tasks:
    - name: build-ue5-game
    taskSpec:
      params:
        - name: Pre-build steps
      steps:
        - image: ubuntu
          name: print-task-status
          script: |
            echo "Hello World"   
  finally:
    - name: Build Binaries
      taskRef:
        name: ue5-build-task-client